/**
 * Auto-generated types from CMS schemas
 * Generated at: 2026-02-06T14:22:20.089Z
 * 
 * DO NOT EDIT THIS FILE MANUALLY
 * Run 'pnpm generate-types' to regenerate
 */

/**
 * Base flexible block type (used when no allowedBlocks are specified)
 */
export type FlexibleBlock = 
  | { type: "shortText"; value: string }
  | { type: "longText"; value: string }
  | { type: "richText"; value: string }
  | { type: "url"; value: string }
  | { type: "youtubeUrl"; value: string }
  | { type: "number"; value: number }
  | { type: "boolean"; value: boolean }
  | { type: "date"; value: string }
  | { type: "media"; value: string }
  | { type: "select"; value: string }
  | { type: "group"; value: any }
  | { type: "blockReference"; value: any }

/**
 * Blog Tags
 * Tags used in the blog
 * @schema blog_tags
 */
export type BlogTagsContent = {
	_id: string
	_creationTime: number
	schemaId: string
	slug?: string
	status: "draft" | "published"
	data: {

    name: string

    slug?: string
	}
}

/**
 * Content Authors
 * Tags used in the blog
 * @schema content_authors
 */
export type ContentAuthorsContent = {
	_id: string
	_creationTime: number
	schemaId: string
	slug?: string
	status: "draft" | "published"
	data: {

    name: string

    picture?: string

    job_title?: string

    company_name?: string

    details?: Array<{

      description?: string

      long_description?: string

      more_details?: Array<{

        long_desc?: string
      }>
    }>
	}
}

/**
 * Blog Posts
 * Blog posts demo
 * @schema blog_posts
 */
export type BlogPostsContent = {
	_id: string
	_creationTime: number
	schemaId: string
	slug?: string
	status: "draft" | "published"
	data: {

    title: string

    slug: string

    featured_image: string

    blocks: Array<FlexibleBlock>

    author: string | ContentAuthorsContent

    tags?: Array<string | BlogTagsContent>

    is_featured?: boolean

    hero?: any

    image: string
	}
}

/**
 * Products
 * Products schema
 * @schema products
 */
export type ProductsContent = {
	_id: string
	_creationTime: number
	schemaId: string
	slug?: string
	status: "draft" | "published"
	data: {

    name: string

    description?: string

    price: number

    image: string
	}
}

/**
 * Listas
 * test
 * @schema listas
 */
export type ListasContent = {
	_id: string
	_creationTime: number
	schemaId: string
	slug?: string
	status: "draft" | "published"
	data: {

    text?: string

    description?: string
	}
}

/**
 * Union of all schema names
 */
export type CMSSchemaName = "blog_tags" | "content_authors" | "blog_posts" | "products" | "listas"

/**
 * Union of all content types
 */
export type CMSContent = BlogTagsContent | ContentAuthorsContent | BlogPostsContent | ProductsContent | ListasContent

/**
 * Helper type to get content type by schema name
 * @example
 * type BlogPost = CMSContentBySchema<'blog_posts'>
 */
export type CMSContentBySchema<T extends CMSSchemaName> = 
  T extends "blog_tags" ? BlogTagsContent :
  T extends "content_authors" ? ContentAuthorsContent :
  T extends "blog_posts" ? BlogPostsContent :
  T extends "products" ? ProductsContent :
  T extends "listas" ? ListasContent :
  never