/**
 * Auto-generated types from CMS schemas and blocks
 * Generated at: 2026-04-08T22:51:42.732Z
 *
 * DO NOT EDIT THIS FILE MANUALLY
 * Run 'pnpm generate-types' to regenerate
 */

/**
 * ISO 8601 date string (YYYY-MM-DD)
 * @example "2024-03-31"
 */
export type ISODate = string & { readonly __brand: "ISODate" }

/**
 * ISO 8601 datetime string (YYYY-MM-DDTHH:mm)
 * @example "2024-03-31T14:30"
 */
export type ISODateTime = string & { readonly __brand: "ISODateTime" }

/**
 * Time string (HH:mm or HH:mm:ss)
 * @example "14:30"
 */
export type TimeString = string & { readonly __brand: "TimeString" }

/**
 * Base flexible block type (used when no allowedBlocks are specified)
 */
export type FlexibleBlock =
  | { type: "shortText"; value: string }
  | { type: "longText"; value: string }
  | { type: "richText"; value: string }
  | { type: "url"; value: { url: string; newWindow?: boolean } }
  | { type: "youtubeUrl"; value: string }
  | { type: "number"; value: number }
  | { type: "boolean"; value: boolean }
  | { type: "date"; value: ISODate }
  | { type: "datetime"; value: ISODateTime }
  | { type: "time"; value: TimeString }
  | { type: "media"; value: string }
  | { type: "select"; value: string }
  | { type: "group"; value: any }
  | { type: "blockReference"; value: any }

// =============================================================================
// SCHEMA CONTENT TYPES
// =============================================================================

/**
 * Blog Tags
 * Tags used in the blog
 * @schema blog_tags
 */
export type BlogTagsContent = {
	_id: string
	_creationTime: number
	schemaId: string
	slug?: string
	status: "draft" | "published"
	data: {

    name: string

    slug?: string

    blocks?: Array<{ type: "blockReference"; value: any } | { type: "media"; value: string } | { type: "richText"; value: string }>

    images?: Array<{

      text?: string

      description?: string
    }>

    multi_references?: string[]

    group_test?: {

      test?: string

      description?: string
    }
	}
}

/**
 * Content Authors
 * Tags used in the blog
 * @schema content_authors
 */
export type ContentAuthorsContent = {
	_id: string
	_creationTime: number
	schemaId: string
	slug?: string
	status: "draft" | "published"
	data: {

    name: string

    picture?: string

    job_title?: string

    company_name?: string

    details?: Array<{

      description?: string

      long_description?: string

      more_details?: Array<{

        long_desc?: string
      }>
    }>
	}
}

/**
 * Blog Posts
 * Blog posts demo
 * @schema blog_posts
 */
export type BlogPostsContent = {
	_id: string
	_creationTime: number
	schemaId: string
	slug?: string
	status: "draft" | "published"
	data: {

    title: string

    slug: string

    featured_image: string

    blocks: Array<FlexibleBlock>

    author: string

    tags?: string[]

    is_featured?: boolean

    hero?: HeroSectionBlock

    image: string

    test_pdf?: any

    test_select?: "One" | "two" | "three" | "four" | "five"
	}
}

/**
 * Products
 * Products schema
 * @schema products
 */
export type ProductsContent = {
	_id: string
	_creationTime: number
	schemaId: string
	slug?: string
	status: "draft" | "published"
	data: {

    name: string

    description?: string

    price: number

    image: string
	}
}

/**
 * Union of all schema names
 */
export type CMSSchemaName = "blog_tags" | "content_authors" | "blog_posts" | "products"

/**
 * Union of all content types
 */
export type CMSContent = BlogTagsContent | ContentAuthorsContent | BlogPostsContent | ProductsContent

/**
 * Helper type to get content type by schema name
 * @example
 * type BlogPost = CMSContentBySchema<'blog_posts'>
 */
export type CMSContentBySchema<T extends CMSSchemaName> =
  T extends "blog_tags" ? BlogTagsContent :
  T extends "content_authors" ? ContentAuthorsContent :
  T extends "blog_posts" ? BlogPostsContent :
  T extends "products" ? ProductsContent :
  never

// =============================================================================
// REUSABLE BLOCK TYPES
// =============================================================================

/**
 * Hero Section
 * test
 * @block hero_section
 */
export type HeroSectionBlock = {

  title?: string

  test?: string
}

/**
 * test
 * test block
 * @block test
 */
export type TestBlock = {

  test?: string
}

/**
 * Union of all block names
 */
export type CMSBlockName = "hero_section" | "test"

/**
 * Union of all block types
 */
export type CMSBlock = HeroSectionBlock | TestBlock

/**
 * Helper type to get block type by block name
 * @example
 * type CallToAction = CMSBlockByName<'call_to_action'>
 */
export type CMSBlockByName<T extends CMSBlockName> =
  T extends "hero_section" ? HeroSectionBlock :
  T extends "test" ? TestBlock :
  never